name: Deliver on 1st of Month

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  build:
    uses: "./.github/workflows/build_cmake.yml"

  deliver:
    name: Delivery
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v4
      - name: Check Download
        run: ls -all

      - name: Make Release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: "Release"
          tag_name: "Tag"
          # body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # - name: Upload OpenSees_Windows
      #   uses: actions/upload-release-asset@v1
      #   env:
      #     GITHUB_TOKEN: ${{ github.token }}
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_name: OpenSees_Windows
      #     asset_path: OpenSees_Windows.zip
      #     asset_content_type: application/x-zip-compressed

      - name: Upload OpenSees_Mac
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: OpenSees_Mac
          asset_path: OpenSees_Mac
          asset_content_type: application/zip

      - name: Upload OpenSees_Ubuntu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_name: OpenSees_Ubuntu
          asset_path: OpenSees_Ubuntu
          asset_content_type: application/zip
